### ISSUE TITLE
[BUG] Scale Subresource "Does not exist" if it's a nil pointer

### ISSUE THREAD

**Issue by ellistarn** [kubernetes/apimachinery#106]
Apologies if this is the wrong SIG. Please redirect me. 

My code attempts to update a scale subresource
```
func (a *Autoscaler) updateScaleTarget(scaleTarget *v1.Scale) error {
	groupResource, err := a.parseGroupResource(a.Spec.ScaleTargetRef)
	if err != nil {
		return fmt.Errorf("parsing group resource for %v, %w", a.Spec.ScaleTargetRef, err)
	}
	if _, err := a.scalesGetter.
		Scales(a.ObjectMeta.Namespace).
		Update(context.TODO(), groupResource, scaleTarget, metav1.UpdateOptions{}); err != nil {
		return fmt.Errorf("updating %v, %w", scaleTarget.ObjectMeta.SelfLink, err)
	}
	return nil
}
```
I see the error
```
Internal error occurred: the spec replicas field ".spec.replicas" does not exist'
```

My CRD snippit shows
```
replicas:
  description: Replicas is the desired number of replicas
  format: int32
  type: integer
```
And my go struct is 
```
Replicas *int32 `json:"replicas,omitempty"`
```
Ideally this would be a *int32 and not an int32 so that 

Everything works normally if the value is not nil.

**Comment by liggitt** [comment]
what does your CRD definition look like? is spec.replicas required or does it have a default value? if not, the server does not know what the current value is for the scale.

from the CRD doc:

> If there is no value under the given path in the custom resource, the `/scale` subresource will return an error on GET.

**Comment by ellistarn** [comment]
The CRD definition is 
```
replicas:
  description: Replicas is the desired number of replicas
  format: int32
  type: integer
```
spec.replicas is not required. If not provided, the desired behavior is to simply not reconcile. I'd expect an error on scale.Get but I'm currently getting it on scale.Update. I agree it should error on GET if it's nil (or perhaps just return nil?).
