### ISSUE TITLE
Error messages for oneOf, allOf, anyOf, not

### ISSUE THREAD

**Issue by dyroberts** [kubernetes/apimachinery#108]
I'm implementing a CRD requiring some semi-complex, but static, input validation in the spec.

For instance, one requirement looks like this:
```
...
hostKey: someHostKey (optional)
hostKeyAlgorithm: some-host-key-algorithm (required if using hostKey)
...
```

To enforce the "x required if y present" I've added the following
```
                  oneOf:
                  - required: ["uri","privateKey"]
                    not:
                      anyOf:
                      - required: [ "hostKey" ]
                      - required: [ "hostKeyAlgorithm" ]
                  - required: ["uri","privateKey","hostKey","hostKeyAlgorithm"]
```

This works, which is great! But the error output when the rule is violated could really use some improvement.
Right now I get
```
The SpringCloudConfigServer "my-config-server" is invalid: 
* : Invalid value: "": "spec.sources" must validate one and only one schema (oneOf). Found none valid
* : Invalid value: "": "spec.sources" must not validate the schema (not)
```

Ideally, it would be nice to get a print-out of the rule that's being violated.
Barring that, the ability to put a title on the inline SchemaObject that is the rule, and then to see that title in the error message, could also work.
