### ISSUE TITLE
Duplicate AdmissionReview - UPDATE operation with validating webhook

### ISSUE THREAD

**Issue by Shashankft9** [kubernetes/apimachinery#116]
I have a `validatingwebhookconfiguration` thats implemented for `v1.Services`, looks like this:
```
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: xxx
    service:
      name: service-ac
      namespace: kube-system
      path: /
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: service-ac.x.x.com
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30

```
Everything works as expected for any CREATE operation, but I see a duplicate admission review going to my webhook handler in the case of UPDATE and when the webhook sends the response as `false` (everything works as expected when the operations is UPDATE and validation responds as `true`).
Although the basic thing works in itself, I still cant get my head around why there might be double invocation here, this is also causing one issue with my prom metrics increment mechanism, since now everytime it increments twice in this particular case. Are there some (hidden?) callbacks that I am missing here?

ref: this looks similar as well https://github.com/open-policy-agent/gatekeeper/issues/278
