### ISSUE TITLE
TestCreateThreeWayJSONMergePatch failure

### ISSUE THREAD

**Issue by eclipseo** [kubernetes/apimachinery#127]
With Golang 1.16.3 on Fedora Rawhide, the following test fails:

```
--- FAIL: TestCreateThreeWayJSONMergePatch (0.01s)
    patch_test.go:683: error in test case: patch array with nil
        expected patch:
        drop:
        - null
        foo:
        - 1
        - false
        - b: 1
        
        got:
        drop: []
        foo:
        - 1
        - false
        - b: 1
        
    patch_test.go:699: error in test case: patch array with nil
        patch application failed:
        original:
        bar:
        - c
        - null
        - null
        - a
        drop: null
        foo:
        - a: true
        - 2
        - false
        
        patch:
        drop: []
        foo:
        - 1
        - false
        - b: 1
        
        expected:
        bar:
        - c
        - null
        - null
        - a
        drop:
        - null
        foo:
        - 1
        - false
        - b: 1
        
        got:
        bar:
        - c
        - null
        - null
        - a
        drop: []
        foo:
        - 1
        - false
        - b: 1
        
FAIL
exit status 1
FAIL	k8s.io/apimachinery/pkg/util/jsonmergepatch	0.010s
```

Each time instead of 
```
        drop:
        - null
```

we've got

```
        drop: []
```
