### ISSUE TITLE
Values for NodeSelectorTerms are evaluated asynchronously

### ISSUE THREAD

**Issue by JamesGAWS** [kubernetes/apimachinery#184]
Currently for AWS Elastic Kubernetes Serivce it is possible to create a deployment with the following spec:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "eks.amazonaws.com/nodegroup"
                operator: In
                values:
                - "${INVALID_VALUE}"
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: 1
        securityContext:
          allowPrivilegeEscalation: false
```

Despite the presence of invalid characters in the nodeSelectorTerms value, the API server will accept this payload. During scheduling, the label [value is validated](https://github.com/kubernetes/apimachinery/blob/95b78024e3feada7739b40426690b4f287933fd8/pkg/util/validation/validation.go#L166) which the label will fail since it [contains invalid characters](https://github.com/kubernetes/apimachinery/blob/2b29434a8c7f13f8908c24756eeac3a0cab3f125/pkg/util/validation/validation.go#L30).

Typical behavior for invalid characters is for the apply call to fail synchronously. Why is this field different?
