### ISSUE TITLE
Encoder does not encode oneof in protobufs correctly

### ISSUE THREAD

**Issue by michaelkipper** [kubernetes/apimachinery#50]
Hi,

I'm working on getting an Istio VirtualService client working, and am running into the following error:

```
admission webhook "pilot.validation.istio.io" denied the request: error decoding configuration: YAML decoding error: gateways:
- test-gateway
hosts:
- '*'
http:
- match:
  - uri:
      MatchType:
        Prefix: /
  route:
  - destination:
      host: test-service
      port:
        Port:
          Number: 8080
 unknown field "MatchType" in v1alpha3.StringMatch 
```

This is because the match should encode to:

```yaml
- match:
  - uri:
    -prefix: /
```

Ultimately, the `encoding/json` package is being used to encode the object, which includes a Protobuf for the VirtualService: https://github.com/kubernetes/apimachinery/blob/90473842928c717082a393d6adceee99889fe8cc/pkg/runtime/serializer/json/json.go#L245-L246

The VirtualService is defined here: https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto

Is there a non-obvious way for me to control the encoding of this object?

I can reproduce the error here: https://github.com/michaelkipper/istio-client-go/pull/6

Thanks!
Michael
