### ISSUE TITLE
Cannot unmarshal str into resource.Quantity

### ISSUE THREAD

**Issue by sunsingerus** [kubernetes/apimachinery#67]
I am trying to unmarshal CR with `type PersistentVolumeClaimSpec struct` and go the following error (for both YAML and JSON):
```
cannot unmarshal !!str `2Gi` into resource.Quantity
```
for 
```
yaml.Unmarshal(str)
```
where yaml is `"gopkg.in/yaml.v2"` and `str` is either YAML or JSON:
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "default-volumeclaimtemplate"
spec:
  defaults:
    templates:
      volumeClaimTemplate: default-volumeclaim-template
  templates:
    volumeClaimTemplates:
      - name: default-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
```
or
```json
{
  "apiVersion": "clickhouse.altinity.com/v1",
  "kind": "ClickHouseInstallation",
  "metadata": {
    "name": "default-volumeclaimtemplate"
  },
  "spec": {
    "defaults":{
      "templates": {
        "volumeClaimTemplate": "default-volumeclaim-template"
      }
    },
    "templates": {
      "volumeClaimTemplates": [
        {
          "name": "default-volumeclaim-template",
          "spec": {
            "accessModes": [
              "ReadWriteOnce"
            ],
            "resources": {
              "requests": {
                "storage": "2Gi"
              }
            }
          }
        }
      ]
    }
  }
}
```
Any ideas how to solve? Thanks in advance!
