### ISSUE TITLE
[Question]  Why don't add yaml tag for `TypeMeta`

### ISSUE THREAD

**Issue by Starnop** [kubernetes/apimachinery#97]
I construct a struct as follows:
```
import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type Demo struct {
   	metav1.TypeMeta   `yaml:",inline"`
	metav1.ObjectMeta `yaml:"metadata,omitempty"`
        ......
}
```

However, when I marshal  `Demo` struct as a YAML file, I got something as follows:

```YAML
apiversion: xxx/xxx
kind: demo
......
```

In fact, the YAML file which expected should be as follows:
 ```YAML
apiVersion: xxx/xxx
kind: demo
......
```

And so do with metav1.ObjectMeta.

With Kubernetes, we usually use the YAML format object. So I am curious about why we don't add YAML tags for [TypeMeta & ObjectMeta](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L55).
